import simpleGit from "simple-git";
import fs from "fs";
import path from "path";
import { config } from "../config";

const git = simpleGit(config.repoPath);

export async function createBranchAndCommit(content: string) {
  const branchName = `orchesus-${Date.now()}`;

  await git.checkoutLocalBranch(branchName);

  const outputPath = path.join(config.repoPath, "ORCHESUS_OUTPUT.md");
  fs.writeFileSync(outputPath, content);

  await git.add(".");
  await git.commit("feat: production PR generated by ORCHESUS");

  return branchName;
}
